export const SET_AUTHED_USER = 'SET_AUTHED_USER';

export const RECEIVE_USERS = 'RECEIVE_USERS';

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_ANSWER = 'ADD_QUESTION_ANSWER';
